#!/usr/bin/env bash
set -e

# sed command used for url code replacement
# this reflects generate_m3u.sh
# duplicated to save redefinition given of frequency of use
replace="sed"
replace+=" -e 's,%20, ,g'"
replace+=" -e 's,%21,!,g'"
replace+=" -e 's,%22,\",g'"
replace+=" -e 's,%23,#,g'"
replace+=" -e 's,%24,$,g'"
replace+=" -e 's,%26,\&,g'"
replace+=' -e "s,%27,'"'"',g"'
replace+=" -e 's,%28,(,g'"
replace+=" -e 's,%29,),g'"
replace+=" -e 's,%5B,[,g'"
replace+=" -e 's,%5D,],g'"
replace+=" -e 's,%7B,{,g'"
replace+=" -e 's,%7D,},g'"

################################################################################
##  functions
################################################################################
## https://stackoverflow.com/a/37840948/201197
#urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }

urldecode() {
    ## if there's no input, use the whole playlist file
    if [[ -z "$1" ]]; then
        eval $replace $playlist_file
    else
        echo "$1" | eval $replace
    fi

}

load_config() {
    QUERIES=()
    config_file=${config_file:-~/.bmmp/config}
    [[ -f "${config_file}" ]] && source "${config_file}"

    KEY_LIST=${KEY_LIST:-l}
    KEY_NEXT=${KEY_NEXT:-n}
    KEY_PREV=${KEY_PREV:-p}
    KEY_QUIT=${KEY_QUIT:-q}
    KEY_RANDOM=${KEY_RANDOM:-r}
    KEY_PLAY_PAUSE=${KEY_PLAY_PAUSE:-s}
}

## look for the playlist in known locations
find_playlist() {
    local possible_playlists=( $playlist_file ~/.bmmp/playlist.m3u playlist.m3u )
    
    for playlist in ${possible_playlists[@]}; do
        if [[ -f $playlist ]]; then
            playlist_file=$playlist
            echo "Reading playlist from $playlist_file"
            return
        fi
    done

    echo "!! No playlist found"
    exit -2
}

## choose the next track to play
choose_next() {
    first=1

    if [[ ! -z "$user_pick" ]]; then
        if [[ ${user_pick:0:1} == "-" || ${user_pick:0:1} == "+" ]]; then
            pick=$(($pick $user_pick))
        else
            pick=$user_pick
        fi
        unset user_pick

        if [[ $pick -lt $first ]]; then
            pick=$first
        elif [[ $pick -gt $list_len ]]; then
            pick=$list_len
        fi

    elif [ "$previous" = true ]; then
        unset previous
        if [[ $pick -gt 1 ]]; then
            pick=$((pick - 1))
        fi

    elif [ "$random" = true ]; then
        ## pick a random track from the list
        if hash jot;  then
            pick=$(jot -r 1 $first $list_len)
        elif hash shuf; then
            pick=$(shuf -n 1 -i $first-$list_len)
        fi

    else
        ## advance to the next track or wrap back to the beginning
        pick=$((pick % list_len + 1))
    fi

    if [[ -z "$list" ]]; then
        url=$(sed "${pick}q;d" "$playlist_file")
    else
        url=$(echo "$list" | sed -n ${pick}p)
    fi
}

collect_arguments() {
    if [[ ! -z "$query" ]]; then
        IFS=';' read -r -a terms <<< "${QUERIES[${query}]}"
    fi

    ## collect query items or use the remaining arguments
    if [[ "${#terms[@]}" -gt 0 ]]; then
        if [[ ! -z "$pattern" ]]; then
            pattern+='|'
        fi
        pattern+='('
        for q in "${terms[@]}"; do
            pattern+="$q)|("
        done
        pattern=${pattern%|(}
    fi
}

## kill the mpg123 process if running
kill_it() {
    if [[ -z "$last_pid" ]]; then
        return
    fi

    if ps -p $last_pid > /dev/null; then
        kill $last_pid
        unset last_pid
        state=stopped
    fi
}

## use mpg123 to play an mp3 by url
play_url() {
    echo "** playing track $pick"

    echo $(urldecode "$url")
    curl -ks "$url" | mpg123 --resync-limit 2048 --long-tag - & last_pid=$!
    state=playing
}

## toggle starting or stopping a url
play_pause() {
    if [[ "$state" == 'playing' ]]; then
        kill_it
    else
        play_url
    fi
}

## toggle the random setting used when choosing the next entry to play
toggle_random() {
    if [ "$random" = true ]; then
        random=false
    else
        random=true
    fi
    echo -e "** set random to $random"
}

## play songs based on a search
play() {
    search

    pick=0
    state=stopped
    while true; do
        echo '--------------------------------------------------------------------------------'
        choose_next

        play_url
        echo '--------------------------------------------------------------------------------'

        while true; do
            read -s -n 1 -t 1 cmd || true

            case $cmd in
                [1-9+-])
                    read -p "Choose track [playing $pick of $list_len]: " -e -i "$cmd" user_pick

                    if [[ ! -z "$user_pick" ]]; then
                        kill_it
                        break
                    fi
                    ;;

                $KEY_LIST) print_list ;;
                $KEY_NEXT) kill_it; break ;;
                $KEY_PREV) previous=true; kill_it; break ;;
                $KEY_QUIT) kill_it; echo '** bye!'; return 0 ;;
                $KEY_RANDOM) toggle_random ;;
                $KEY_PLAY_PAUSE) play_pause ;;
                \?) usage ;;
            esac

            ## if should be playing, but is missing mpg123 process, assume an
            ## error happend, so break the loop to start the next track
            if [[ "$state" == "playing" && -z "$(pgrep mpg123)" ]]; then
                break
            fi
        done
    done
}

## print the playlist
print_list() {
    echo "$(urldecode "$list")" | less -R --chop-long-lines --LINE-NUMBERS +${pick}g
}

## search the playlist
search() {
    if [[ -z "$pattern" ]]; then
        echo "Using entire playlist..."
        unset list
        list_len=$(sed -n '$=' "$playlist_file")
    else
        # replace space with 'any char'
        echo "Searching for '$pattern'..."
        local esc_pattern="${pattern//[\.]/\\.}"  # replace dots with escaped dots for explicit match
        esc_pattern="${esc_pattern//[ ]/.+}"      # replace spaces with .+ for fuzzy matching
        #echo "Using pattern: ${esc_pattern}"
        list=$(grep -Ei "$esc_pattern" "$playlist_file" | sort)
        if [[ -z "$list" ]]; then
            echo "!! Did not find results for '${pattern}'"
            exit -1
        fi
        list_len=$(echo "$list" | sed -n '$=')
    fi
}

## print usage details
usage() {
    echo '****************************************'
    echo ' :arguments:'
    echo '****************************************'
    echo ' -h   show help and usage'
    echo ' -p   location of the playlist file to use'
    echo ' -r   turn on random play'
    echo ' -s   specify multiple search terms (can be repeated)'
    echo
    echo '****************************************'
    echo ' :runtime:'
    echo '****************************************'
    echo ' ?      - show usage'
    echo ' [1-9]+ - choose entry from playlist'
    echo " $KEY_LIST      - print the playlist"
    echo " $KEY_NEXT      - next track"
    echo " $KEY_PREV      - previous track"
    echo " $KEY_QUIT      - quit"
    echo " $KEY_RANDOM      - toggle random play"
    echo " $KEY_PLAY_PAUSE      - play and pause"
    echo '****************************************'
}

################################################################################
##  main
################################################################################

terms=()
while getopts :hp:q:rs: option; do
    case $option in
        c) config_file=$OPTARG ;;
        h) usage; exit 0 ;;
        p) playlist_file=$OPTARG ;;
        q) query=$OPTARG ;;
        r) random=true ;;
        s) terms+=("$OPTARG") ;;
    esac
done

shift "$((OPTIND-1))"
terms+=("$@")

load_config
find_playlist

collect_arguments
play
